const data = {
  products: [
    {
      name: "Free Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A shirt",
    },
    {
      name: "Free Shirt2",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A shirt",
    },
    {
      name: "Free Shirt3",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A shirt",
    },
    {
      name: "Free Shirt4",
      category: "Shirts",
      image: "/images/shirt4.jpg",
      price: 70,
      brand: "Jakel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A shirt",
    },
  ],
};

export default data;
